import styles from '../styles/Home.module.css'

export const metadata = {
  title: '诺',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <div className="container">
      <main className={styles.main}>
        <h1 className="text-center">Welcome to <a href="https://nuo.bo7.co">诺</a></h1>

        <h4 className="text-center">
          <code>Get started</code>
        </h4>
      </main>

      <footer className="text-center">
        <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
           target="_blank"
           rel="noopener noreferrer">
          Powered by Vercel
        </a>
      </footer>
    </div>
  )
}
